// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"gorm.io/gorm"
	"ybg-backend-go/core/delivery/http"
	"ybg-backend-go/core/repository"
	"ybg-backend-go/core/usecase"
)

// Injectors from wire.go:

// Injector Functions
func InitializeUserHandler(db *gorm.DB) *http.UserHandler {
	userRepository := repository.NewUserRepository(db)
	pointRepository := repository.NewPointRepository(db)
	userUsecase := usecase.NewUserUsecase(userRepository, pointRepository)
	userHandler := http.NewUserHandler(userUsecase)
	return userHandler
}

func InitializeProductHandler(db *gorm.DB) *http.ProductHandler {
	productRepository := repository.NewProductRepository(db)
	productUsecase := usecase.NewProductUsecase(productRepository)
	productHandler := http.NewProductHandler(productUsecase)
	return productHandler
}

func InitializeNewsHandler(db *gorm.DB) *http.NewsHandler {
	newsRepository := repository.NewNewsRepository(db)
	newsUsecase := usecase.NewNewsUsecase(newsRepository)
	newsHandler := http.NewNewsHandler(newsUsecase)
	return newsHandler
}

func InitializeBrandHandler(db *gorm.DB) *http.BrandHandler {
	brandRepository := repository.NewBrandRepository(db)
	brandUsecase := usecase.NewBrandUsecase(brandRepository)
	brandHandler := http.NewBrandHandler(brandUsecase)
	return brandHandler
}

func InitializeCategoryHandler(db *gorm.DB) *http.CategoryHandler {
	categoryRepository := repository.NewCategoryRepository(db)
	categoryUsecase := usecase.NewCategoryUsecase(categoryRepository)
	categoryHandler := http.NewCategoryHandler(categoryUsecase)
	return categoryHandler
}

func InitializePointHandler(db *gorm.DB) *http.PointHandler {
	pointRepository := repository.NewPointRepository(db)
	pointUsecase := usecase.NewPointUsecase(pointRepository)
	pointHandler := http.NewPointHandler(pointUsecase)
	return pointHandler
}

// wire.go:

// Definisikan semua Set Dependency
var userSet = wire.NewSet(repository.NewUserRepository, repository.NewPointRepository, usecase.NewUserUsecase, http.NewUserHandler)

var productSet = wire.NewSet(repository.NewProductRepository, usecase.NewProductUsecase, http.NewProductHandler)

var newsSet = wire.NewSet(repository.NewNewsRepository, usecase.NewNewsUsecase, http.NewNewsHandler)

var brandSet = wire.NewSet(repository.NewBrandRepository, usecase.NewBrandUsecase, http.NewBrandHandler)

var categorySet = wire.NewSet(repository.NewCategoryRepository, usecase.NewCategoryUsecase, http.NewCategoryHandler)

var pointSet = wire.NewSet(repository.NewPointRepository, usecase.NewPointUsecase, http.NewPointHandler)
